version: "3.9"

services:
  java_app:
    container_name: java_app
    image: backend:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=jdbc:mysql://java_db:3306/quizwiz?serverTimezone=UTC
      - DATABASE_USERNAME=root
      - DATABASE_PASSWORD=
    restart: always
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
      - MYSQL_DB=quizwiz
    volumes:
      - mysql_data:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: my_phpmyadmin
    environment:
      PMA_HOST: java_db
      PMA_USER: root
      PMA_PASSWORD:
    ports:
      - "8081:80"
    depends_on:
      - java_db
  
volumes:
  mysql_data: