version: "3.9"

services:
  java_app:
    container_name: java_app
    image: backend:1.0
    build: .
    ports:
      - "8080:8080"
    environment:
      - DATABASE_URL=${URL}
      - DATABASE_USERNAME=${USER}
      - DATABASE_PASSWORD=${PASSWORD}
    restart: always
    depends_on:
      - java_db
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=TRUE
      - MYSQL_DB=quizwiz
    volumes:
      - mysql_data:/var/lib/mysql
  
volumes:
  mysql_data: